title: Sakai Portfolio
description: Portfolio of Game Engineer
baseurl: "/portfolio-v2"
url: "https://sakai8121.github.io"
collections:
  research:
      output: true
      permalink: /research/:title/
  games:
    output: true
    permalink: /games/:path/
  work:
    output: true
    permalink: /work/:path/
